# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ressources/InputTab.ui'
#
# Created: Mon Nov  4 15:28:17 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(792, 647)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(200, 200))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 360, 231, 151))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout.addWidget(self.checkBox)
        self.formLayoutWidget_2 = QtGui.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(380, 540, 231, 91))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setContentsMargins(0, -1, -1, -1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.pushButton_start = QtGui.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(840, 580, 131, 32))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 390, 313, 242))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_esp = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_esp.setObjectName(_fromUtf8("pushButton_esp"))
        self.gridLayout.addWidget(self.pushButton_esp, 4, 2, 1, 1)
        self.lineEdit_esp = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_esp.setObjectName(_fromUtf8("lineEdit_esp"))
        self.gridLayout.addWidget(self.lineEdit_esp, 4, 1, 1, 1)
        self.pushButton_omni = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_omni.setObjectName(_fromUtf8("pushButton_omni"))
        self.gridLayout.addWidget(self.pushButton_omni, 3, 2, 1, 1)
        self.lineEdit_aluRegions = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_aluRegions.setObjectName(_fromUtf8("lineEdit_aluRegions"))
        self.gridLayout.addWidget(self.lineEdit_aluRegions, 5, 1, 1, 1)
        self.label_refGenome = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_refGenome.sizePolicy().hasHeightForWidth())
        self.label_refGenome.setSizePolicy(sizePolicy)
        self.label_refGenome.setObjectName(_fromUtf8("label_refGenome"))
        self.gridLayout.addWidget(self.label_refGenome, 0, 0, 1, 1)
        self.pushButton_dbSNP = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_dbSNP.setObjectName(_fromUtf8("pushButton_dbSNP"))
        self.gridLayout.addWidget(self.pushButton_dbSNP, 1, 2, 1, 1)
        self.pushButton_aluRegion = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_aluRegion.sizePolicy().hasHeightForWidth())
        self.pushButton_aluRegion.setSizePolicy(sizePolicy)
        self.pushButton_aluRegion.setObjectName(_fromUtf8("pushButton_aluRegion"))
        self.gridLayout.addWidget(self.pushButton_aluRegion, 5, 2, 1, 1)
        self.lineEdit_refGenome = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_refGenome.sizePolicy().hasHeightForWidth())
        self.lineEdit_refGenome.setSizePolicy(sizePolicy)
        self.lineEdit_refGenome.setObjectName(_fromUtf8("lineEdit_refGenome"))
        self.gridLayout.addWidget(self.lineEdit_refGenome, 0, 1, 1, 1)
        self.label_dbSNP = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dbSNP.sizePolicy().hasHeightForWidth())
        self.label_dbSNP.setSizePolicy(sizePolicy)
        self.label_dbSNP.setObjectName(_fromUtf8("label_dbSNP"))
        self.gridLayout.addWidget(self.label_dbSNP, 1, 0, 1, 1)
        self.label_aluRegions = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_aluRegions.sizePolicy().hasHeightForWidth())
        self.label_aluRegions.setSizePolicy(sizePolicy)
        self.label_aluRegions.setObjectName(_fromUtf8("label_aluRegions"))
        self.gridLayout.addWidget(self.label_aluRegions, 5, 0, 1, 1)
        self.pushButton_refGenome = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_refGenome.setObjectName(_fromUtf8("pushButton_refGenome"))
        self.gridLayout.addWidget(self.pushButton_refGenome, 0, 2, 1, 1)
        self.label_hapmap = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hapmap.sizePolicy().hasHeightForWidth())
        self.label_hapmap.setSizePolicy(sizePolicy)
        self.label_hapmap.setObjectName(_fromUtf8("label_hapmap"))
        self.gridLayout.addWidget(self.label_hapmap, 2, 0, 1, 1)
        self.label_esp = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esp.sizePolicy().hasHeightForWidth())
        self.label_esp.setSizePolicy(sizePolicy)
        self.label_esp.setObjectName(_fromUtf8("label_esp"))
        self.gridLayout.addWidget(self.label_esp, 4, 0, 1, 1)
        self.lineEdit_dbSNP = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dbSNP.setObjectName(_fromUtf8("lineEdit_dbSNP"))
        self.gridLayout.addWidget(self.lineEdit_dbSNP, 1, 1, 1, 1)
        self.label_omni = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_omni.sizePolicy().hasHeightForWidth())
        self.label_omni.setSizePolicy(sizePolicy)
        self.label_omni.setObjectName(_fromUtf8("label_omni"))
        self.gridLayout.addWidget(self.label_omni, 3, 0, 1, 1)
        self.pushButton_hapmap = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_hapmap.setObjectName(_fromUtf8("pushButton_hapmap"))
        self.gridLayout.addWidget(self.pushButton_hapmap, 2, 2, 1, 1)
        self.lineEdit_hapmap = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_hapmap.setObjectName(_fromUtf8("lineEdit_hapmap"))
        self.gridLayout.addWidget(self.lineEdit_hapmap, 2, 1, 1, 1)
        self.lineEdit_omni = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_omni.setObjectName(_fromUtf8("lineEdit_omni"))
        self.gridLayout.addWidget(self.lineEdit_omni, 3, 1, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 531, 181))
        self.label.setAutoFillBackground(False)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../icons/RNAeditor.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_8.setText(_translate("Form", "Settings", None))
        self.checkBox_2.setToolTip(_translate("Form", "Overwrite exisitng Files", None))
        self.checkBox_2.setText(_translate("Form", "Overwrite", None))
        self.checkBox.setToolTip(_translate("Form", "Delete Temporary Files", None))
        self.checkBox.setText(_translate("Form", "Delete Temp", None))
        self.label_9.setText(_translate("Form", "Output", None))
        self.label_10.setText(_translate("Form", "outfile Prefix", None))
        self.pushButton_start.setText(_translate("Form", "Start", None))
        self.pushButton_esp.setText(_translate("Form", "...", None))
        self.pushButton_omni.setText(_translate("Form", "...", None))
        self.label_refGenome.setText(_translate("Form", "ref. Genome:", None))
        self.pushButton_dbSNP.setText(_translate("Form", "...", None))
        self.pushButton_aluRegion.setText(_translate("Form", "...", None))
        self.label_dbSNP.setText(_translate("Form", "dbSNP:", None))
        self.label_aluRegions.setText(_translate("Form", "Alu Regions:", None))
        self.pushButton_refGenome.setText(_translate("Form", "...", None))
        self.label_hapmap.setText(_translate("Form", "Hapmap:", None))
        self.label_esp.setText(_translate("Form", "ESP:", None))
        self.label_omni.setText(_translate("Form", "Omni:", None))
        self.pushButton_hapmap.setText(_translate("Form", "...", None))

